# Generated by Django 2.0 on 2017-12-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('food_pic', models.ImageField(blank=True, upload_to='food/')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_img', models.ImageField(blank=True, upload_to='restaurant/')),
                ('name', models.CharField(max_length=200)),
                ('rest_desc', models.CharField(max_length=200)),
                ('menu', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('website_url', models.CharField(blank=True, max_length=500)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
            ],
        ),
    ]
