# Generated by Django 2.0 on 2017-12-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='food',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='food',
            field=models.ManyToManyField(to='food.Food'),
        ),
    ]
